# Generated by Django 5.2.9 on 2026-01-05 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_about_sociallinks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sociallinks',
            options={'verbose_name_plural': 'social'},
        ),
    ]
